[Main]
; 1 = ativo, 0 = desativado
Enable = 1

; Gangue que sera alterada (0 = Mafia)
Gang = 0

; Arma que sera substituida e arma nova (GTA III: 2 = Colt45, 3 = Uzi, 4 = Shotgun, 5 = AK-47, 6 = M16)
FromWeapon = 4
ToWeapon = 3

; 1 = gera MafiaUzi.log ao lado do .asi (para diagnostico)
Log = 0
