[Main]
; 1 = enabled, 0 = disabled
Enable = 1

; Gang to be modified (0 = Mafia)
Gang = 0

; Weapon to be replaced and new weapon (GTA III: 2 = Colt45, 3 = Uzi, 4 = Shotgun, 5 = AK-47, 6 = M16)
FromWeapon = 4
ToWeapon = 3

; 1 = generates MafiaUzi.log next to the .asi file (for diagnostics)
Log = 0
